import {
  BarChart2,
  ChevronsDown,
  Cpu,
  Database,
  LayoutDashboard,
  Play,
  ScanSearch,
  ShieldCheck,
  Zap,
} from "lucide-react"
import type { QuickRunStep, Section } from "../Help"

export const quickRunSteps: QuickRunStep[] = [
  {
    number: 1,
    title: "Register your database",
    description:
      "Go to the **Databases** page and add a new entry. Provide a recognisable **name** and a valid **connection string**. Watchtower only reads your schema — it never touches your live data rows.",
    icon: <Database className="size-4" />,
    tip: "You only need to do this once per environment. Skip to step 2 if you already have a database registered.",
  },
  {
    number: 2,
    title: "Warm up the engine",
    description:
      "On the **Dashboard**, check the **Model Initialization** card. If the engine is cold, trigger a warm-up so it's ready when your check lands. This runs in the background.",
    icon: <Cpu className="size-4" />,
    tip: "A cold engine won't block your check — it just means the first assertion may take a little longer to appear.",
  },
  {
    number: 3,
    title: "Launch a compliance check",
    description:
      "Hit **Run Compliance Check** — available on both the Dashboard and the Assertions page. Select your **Client Database** and the **Compliance Framework** you want to evaluate against, then confirm.",
    icon: <Play className="size-4" />,
  },
  {
    number: 4,
    title: "Watch the stream",
    description:
      "On the Assertions page, results will begin streaming in real time. Use **Jump to Running** to snap the view to the assertion currently being generated by the engine.",
    icon: <ChevronsDown className="size-4" />,
    tip: "If the feed looks stale, hit Refresh List to force a poll of the latest state.",
  },
  {
    number: 5,
    title: "Review failures & recommendations",
    description:
      "Click any failed assertion in the left pane. The right pane loads the full report: the SQL query the engine ran, its output, and an **AI-generated recommendation** explaining exactly what went wrong.",
    icon: <ScanSearch className="size-4" />,
  },
]

export const sections: Section[] = [
  {
    id: "quick-run",
    icon: <Zap className="size-4" />,
    title: "Quick Run",
    subsections: [],
  },
  {
    id: "dashboard",
    icon: <LayoutDashboard className="size-4" />,
    title: "The Dashboard",
    subsections: [
      {
        title: "At a glance",
        content: `The dashboard is your control room. Four distinct metrics and actions give you the current system state at a glance:

- **Compliance Status** — A shortcut to launch a new compliance check instantly without leaving the dashboard view as well as view the status of the engine.
- **Database Count** — The total number of client databases currently registered and monitored within the system.
- **Framework Count** — The number of compliance standards and security baselines available to execute against your targets.
- **Model Initialization** — Displays whether the underlying AI engine is warm and fully operational. Trigger an explicit warm-up here before initiating your first check of the session to ensure maximum processing speed.`,
      },
      {
        title: "Recent checks",
        content: `Below the cards, the dashboard lists your five most recent compliance checks. Each entry shows the framework, database, date, and who ran it.\n\nClicking any check takes you directly to the Assertions page, pre-filtered to show only the assertions from that run. This is the fastest way to revisit a previous result.`,
      },
    ],
  },
  {
    id: "setup",
    icon: <Database className="size-4" />,
    title: "Setting Up Databases",
    subsections: [
      {
        title: "Adding a database",
        content: `Maps to the **Databases** page and add a new entry. You need two things:\n\n1. A **name** — something you'll recognise, like "production-postgres" or "staging-mysql".\n2. A **connection string** — Watchtower uses this to read the schema definition of your database.\n\n> **Note:** Watchtower analyses schema structure only. It does not read, store, or transmit your actual data rows.`,
      },
      {
        title: "Removing a database",
        content: `You can delete a database from the Databases page at any time. This removes it from your active list and prevents it from appearing in future check forms.\n\nDeleting a database does **not** remove historical schemas or past compliance checks associated with it. All prior results remain intact.`,
      },
    ],
  },
  {
    id: "running-checks",
    icon: <ShieldCheck className="size-4" />,
    title: "Running Checks",
    subsections: [
      {
        title: "Starting a check",
        content: `Hit **Run Compliance Check** — the button appears on both the Dashboard and the Assertions page. A form will prompt you for:\n\n1. **Client Database** — which registered database to evaluate.\n2. **Compliance Framework** — the regulatory standard to check against.\n\nConfirm and the pipeline starts. In the Assertions page, results will stream in as they're generated.`,
      },
      {
        title: "Navigating a live stream",
        content: `While a check is running, assertions appear in the left pane one by one as the engine processes each rule. Two controls help you stay oriented:\n\n- **Jump to Running** — scrolls the list instantly to the assertion currently being generated. Useful when a check has many rules and you want to watch the live frontier.\n- **Refresh List** — manually polls for the latest state. Use this if the feed appears to have stalled.\n\nThe stream closes automatically once all assertions are complete.`,
      },
      {
        title: "Check history",
        content: `Every check you run is permanently stored and accessible directly from the Compliance Checks history page.\n\nExpanding any past run reveals a detailed breakdown of its execution parameters, timestamps, and overall pass rates. Click "Jump to assertions" to navigate directly to the Assertions view filtered specifically to that execution's unique state.`,
      },
    ],
  },
  {
    id: "assertions",
    icon: <ScanSearch className="size-4" />,
    title: "Analyzing Assertions",
    subsections: [
      {
        title: "The split-pane workspace",
        content: `The Assertions page is structured as an interactive split-pane environment for rapid security analysis:

- **Left Pane — The Assertion Sidebar.** This column renders individual assertion cards. Each card displays its unique ID, the raw SQL query string executed against your schema, the associated Compliance Check ID, the target Client Database, and the framework ruleset applied.
- **Right Pane — The Assertion Report.** Selecting any assertion card from the sidebar loads its complete diagnostic breakdown inside this view, pinpointing query outputs and security gaps.`,
      },
      {
        title: "Real-time streaming & results",
        content: `Assertions feature dynamic status indicators based on real-time engine states, visually color-coded for fast reading:

- **Passed (Green Border)** — The database completely satisfied the ruleset. No vulnerability was detected, and no corrective actions are required.
- **Failed (Red Border)** — A security or architectural rule was violated. The interface immediately surfaces detailed compliance metrics.
- **Active Streaming (Spinning Disc/Loader)** — The validation engine is actively processing the assertion or streaming live AI recommendations asynchronously. You can track real-time engine phases (\`fetching\`, \`generating\`, \`analyzing\`, \`done\`) directly from the status indicator as well as last running time.`,
      },
      //       {
      //         title: "Interpreting live AI recommendations",
      //         content: `When a rule fails, WatchtowerDB doesn't just report the error—it resolves it. If an assertion is flagged as failed, the system invokes an asynchronous AI engine to generate mitigation strategies.

      // If a background check triggers while you are browsing, a "Jump to Streaming" shortcut appears in the header, letting you snap focus instantly to the active assertion to watch the AI output stream into the report in real time.`,
      //       },
    ],
  },
  {
    id: "analytics",
    icon: <BarChart2 className="size-4" />,
    title: "Analytics & Trends",
    subsections: [
      {
        title: "Assertions summary",
        content: `The Assertions Summary gives you a macro view across all your compliance history. Rather than looking at one check at a time, this view aggregates results to surface patterns:\n\n- Historical pass rates over time.\n- Which rules fail most frequently across runs.\n- Compliance health per database or framework.\n\nUse this to identify systemic issues — rules that reliably fail are worth fixing at the schema level, not just patching run by run.`,
      },
    ],
  },
]
