import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  BarChart2,
  CheckCircle2,
  ChevronDown,
  ChevronsDown,
  Cpu,
  Database,
  HelpCircle,
  LayoutDashboard,
  Play,
  RefreshCw,
  ScanSearch,
  Search,
  ShieldCheck,
  Terminal,
  XCircle,
  Zap,
} from "lucide-react"
import { useEffect, useMemo, useState } from "react"

// ─── Types ────────────────────────────────────────────────────────────────────

interface Subsection {
  title: string
  content: string
}

interface Section {
  id: string
  icon: React.ReactNode
  title: string
  subsections: Subsection[]
}

interface QuickRunStep {
  number: number
  title: string
  description: string
  icon: React.ReactNode
  tip?: string
}

// ─── Quick Run steps ──────────────────────────────────────────────────────────

const quickRunSteps: QuickRunStep[] = [
  {
    number: 1,
    title: "Register your database",
    description:
      "Go to the **Databases** page and add a new entry. Provide a recognisable **name** and a valid **connection string**. Watchtower only reads your schema — it never touches your live data rows.",
    icon: <Database className="size-4" />,
    tip: "You only need to do this once per environment. Skip to step 2 if you already have a database registered.",
  },
  {
    number: 2,
    title: "Warm up the engine",
    description:
      "On the **Dashboard**, check the **Model Initialization** card. If the engine is cold, trigger a warm-up so it's ready when your check lands. This runs in the background.",
    icon: <Cpu className="size-4" />,
    tip: "A cold engine won't block your check — it just means the first assertion may take a little longer to appear.",
  },
  {
    number: 3,
    title: "Launch a compliance check",
    description:
      "Hit **Run Compliance Engine** — available on both the Dashboard and the Assertions page. Select your **Client Database** and the **Compliance Framework** you want to evaluate against, then confirm.",
    icon: <Play className="size-4" />,
  },
  {
    number: 4,
    title: "Watch the stream",
    description:
      "The Assertions page opens and results begin streaming in real time. Use **Jump to Running** to snap the view to the assertion currently being generated by the engine.",
    icon: <ChevronsDown className="size-4" />,
    tip: "If the feed looks stale, hit Refresh List to force a poll of the latest state.",
  },
  {
    number: 5,
    title: "Review failures & recommendations",
    description:
      "Click any failed assertion in the left pane. The right pane loads the full report: the SQL query the engine ran, its output, and an **AI-generated recommendation** explaining exactly what to fix.",
    icon: <ScanSearch className="size-4" />,
  },
]

// ─── Data ─────────────────────────────────────────────────────────────────────

const sections: Section[] = [
  {
    id: "quick-run",
    icon: <Zap className="size-4" />,
    title: "Quick Run",
    subsections: [],
  },
  {
    id: "dashboard",
    icon: <LayoutDashboard className="size-4" />,
    title: "The Dashboard",
    subsections: [
      {
        title: "At a glance",
        content: `The dashboard is your control room. Four cards give you the current system state:

- **Model Initialization** — shows whether the AI engine is warm and ready. Trigger a warm-up here before your first check of the session.
- **Database count** — total client databases registered in the system.
- **Framework count** — number of compliance standards available to run against.
- **Run Compliance Engine** — a shortcut to launch a new check without leaving the dashboard.`,
      },
      {
        title: "Recent checks",
        content: `Below the cards, the dashboard lists your five most recent compliance checks. Each entry shows the framework, database, date, and who ran it.

Clicking any check takes you directly to the Assertions page, pre-filtered to show only the assertions from that run. This is the fastest way to revisit a previous result.`,
      },
    ],
  },
  {
    id: "setup",
    icon: <Database className="size-4" />,
    title: "Setting Up Databases",
    subsections: [
      {
        title: "Adding a database",
        content: `Navigate to the **Databases** page and add a new entry. You need two things:

1. A **name** — something you'll recognise, like "production-postgres" or "staging-mysql".
2. A **connection string** — Watchtower uses this to read the schema definition of your database.

> **Note:** Watchtower analyses schema structure only. It does not read, store, or transmit your actual data rows.`,
      },
      {
        title: "Removing a database",
        content: `You can delete a database from the Databases page at any time. This removes it from your active list and prevents it from appearing in future check forms.

Deleting a database does **not** remove historical schemas or past compliance checks associated with it. All prior results remain intact.`,
      },
    ],
  },
  {
    id: "running-checks",
    icon: <ShieldCheck className="size-4" />,
    title: "Running Checks",
    subsections: [
      {
        title: "Starting a check",
        content: `Hit **Run Compliance Engine** — the button appears on both the Dashboard and the Assertions page. A form will prompt you for:

1. **Client Database** — which registered database to evaluate.
2. **Compliance Framework** — the regulatory standard to check against.

Confirm and the pipeline starts. You'll be taken to the Assertions page where results stream in as they're generated.`,
      },
      {
        title: "Navigating a live stream",
        content: `While a check is running, assertions appear in the left pane one by one as the engine processes each rule. Two controls help you stay oriented:

- **Jump to Running** — scrolls the list instantly to the assertion currently being generated. Useful when a check has many rules and you want to watch the live frontier.
- **Refresh List** — manually polls for the latest state. Use this if the feed appears to have stalled.

The stream closes automatically once all assertions are complete.`,
      },
      {
        title: "Check history",
        content: `Every check you run is stored and accessible from the Dashboard's recent checks list or by navigating to the Assertions page directly. Checks are ordered newest first.

Clicking a past check from the Dashboard filters the Assertions page to that specific run, so you can compare results across different dates or frameworks.`,
      },
    ],
  },
  {
    id: "assertions",
    icon: <ScanSearch className="size-4" />,
    title: "Analyzing Assertions",
    subsections: [
      {
        title: "The split-pane workspace",
        content: `The Assertions page is split into two panes:

- **Left — the check list.** Each card summarises a compliance check: total rules evaluated, passed count, failed count, pass rate percentage, timestamp, user, framework, and client database.
- **Right — the assertion report.** Selecting a check from the left pane loads the full breakdown here: the SQL query the engine ran, its output, and an AI-generated recommendation for every failed rule.

The right pane stays empty until you select a check.`,
      },
      {
        title: "Reading an assertion",
        content: `Each rule in the report has three fields:

- **Result** — pass or fail. A failed assertion means the rule was violated.
- **SQL query** — the exact query the engine executed against your schema to test the rule.
- **Recommendation** — generated asynchronously by the AI. If it shows as pending, the engine is still working. Refresh the report after a moment.`,
      },
      {
        title: "Filtering by check",
        content: `The Assertions page can be scoped to a single compliance check. This happens automatically when you click a recent check on the Dashboard, but you can also apply the filter manually from within the page.

Filtering by check is the most useful view when debugging: you see exactly which rules passed and failed in that specific run, with no noise from other checks.`,
      },
    ],
  },
  {
    id: "analytics",
    icon: <BarChart2 className="size-4" />,
    title: "Analytics & Trends",
    subsections: [
      {
        title: "Assertions summary",
        content: `The Assertions Summary gives you a macro view across all your compliance history. Rather than looking at one check at a time, this view aggregates results to surface patterns:

- Historical pass rates over time.
- Which rules fail most frequently across runs.
- Compliance health per database or framework.

Use this to identify systemic issues — rules that reliably fail are worth fixing at the schema level, not just patching run by run.`,
      },
    ],
  },
]

// ─── Text highlighter ─────────────────────────────────────────────────────────

function TextHighlighter({ text, search }: { text: string; search: string }) {
  if (!search.trim()) return <>{text}</>

  const escapedSearch = search.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&")
  const regex = new RegExp(`(${escapedSearch})`, "gi")
  const parts = text.split(regex)

  return (
    <>
      {parts.map((part, i) =>
        regex.test(part) ? (
          <mark
            key={i}
            className="text-foreground rounded-sm bg-amber-500/25 px-0.5 font-medium mix-blend-multiply dark:bg-amber-500/40 dark:mix-blend-screen"
          >
            {part}
          </mark>
        ) : (
          part
        ),
      )}
    </>
  )
}

// ─── Inline markdown renderer ─────────────────────────────────────────────────

function InlineMarkdown({ text, highlight = "" }: { text: string; highlight?: string }) {
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g)
  return (
    <>
      {parts.map((part, i) => {
        if (part.startsWith("**") && part.endsWith("**")) {
          return (
            <strong key={i} className="text-foreground font-semibold">
              <TextHighlighter text={part.slice(2, -2)} search={highlight} />
            </strong>
          )
        }
        if (part.startsWith("`") && part.endsWith("`")) {
          return (
            <code
              key={i}
              className="bg-muted text-muted-foreground rounded px-1.5 py-0.5 font-mono text-xs font-medium"
            >
              <TextHighlighter text={part.slice(1, -1)} search={highlight} />
            </code>
          )
        }
        return (
          <span key={i}>
            <TextHighlighter text={part} search={highlight} />
          </span>
        )
      })}
    </>
  )
}

// ─── Content renderer ─────────────────────────────────────────────────────────

function SubsectionContent({ content, highlight = "" }: { content: string; highlight?: string }) {
  const blocks = content.split("\n\n")

  return (
    <div className="text-muted-foreground flex flex-col gap-4 text-sm leading-relaxed">
      {blocks.map((block, i) => {
        if (block.trim().startsWith("> ")) {
          return (
            <div
              key={i}
              className="border-primary/60 bg-muted/50 my-1 rounded-lg border-l-4 px-4 py-3"
            >
              <div className="text-foreground text-sm">
                <InlineMarkdown text={block.replace(/^>\s*/, "")} highlight={highlight} />
              </div>
            </div>
          )
        }

        if (block.trim().match(/^\d+\./)) {
          const items = block
            .split("\n")
            .filter(Boolean)
            .map((l) => l.replace(/^\d+\.\s*/, ""))
          return (
            <ol key={i} className="ml-5 list-outside list-decimal space-y-2">
              {items.map((item, ii) => (
                <li key={ii} className="pl-1">
                  <InlineMarkdown text={item} highlight={highlight} />
                </li>
              ))}
            </ol>
          )
        }

        if (block.trim().match(/^-\s/)) {
          const items = block
            .split("\n")
            .filter(Boolean)
            .map((l) => l.replace(/^-\s*/, ""))
          return (
            <ul key={i} className="ml-5 list-outside list-disc space-y-2">
              {items.map((item, ii) => (
                <li key={ii} className="pl-1">
                  <InlineMarkdown text={item} highlight={highlight} />
                </li>
              ))}
            </ul>
          )
        }

        return (
          <p key={i}>
            <InlineMarkdown text={block} highlight={highlight} />
          </p>
        )
      })}
    </div>
  )
}

// ─── Subsection accordion ─────────────────────────────────────────────────────

function SubsectionAccordion({ sub }: { sub: Subsection }) {
  const [open, setOpen] = useState(true)

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <div className="border-border/60 bg-card overflow-hidden rounded-lg border shadow-sm transition-all duration-200 hover:shadow-md">
        <CollapsibleTrigger className="hover:bg-muted/40 flex w-full items-center justify-between px-5 py-4 text-left transition-colors">
          <span className="text-foreground text-sm font-semibold tracking-tight">{sub.title}</span>
          <ChevronDown
            className={`text-muted-foreground size-4 transition-transform duration-200 ease-in-out ${
              open ? "rotate-180" : ""
            }`}
          />
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="border-border/40 bg-muted/10 border-t px-5 pt-4 pb-5">
            <SubsectionContent content={sub.content} />
          </div>
        </CollapsibleContent>
      </div>
    </Collapsible>
  )
}

// ─── Quick Run section ────────────────────────────────────────────────────────

function QuickRunSection() {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-2 space-y-6 duration-300">
      <div className="border-border/40 mb-8 flex items-center gap-4 border-b pb-5">
        <div className="bg-primary/10 text-primary flex h-10 w-10 items-center justify-center rounded-xl shadow-inner">
          <Zap className="size-4" />
        </div>
        <div>
          <h1 className="text-foreground text-2xl font-bold tracking-tight">Quick Run</h1>
          <p className="text-muted-foreground mt-0.5 text-xs">Watchtower Control Hub Guide</p>
        </div>
      </div>

      <p className="text-muted-foreground text-sm leading-relaxed">
        New here? Follow these five steps to go from zero to a full compliance report.
      </p>

      <div className="flex flex-col gap-3">
        {quickRunSteps.map((step, idx) => (
          <div key={step.number} className="flex gap-4">
            {/* Step spine */}
            <div className="flex shrink-0 flex-col items-center">
              <div className="bg-primary text-primary-foreground z-10 flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-bold">
                {step.number}
              </div>
              {idx < quickRunSteps.length - 1 && <div className="bg-border/60 mt-1 w-px flex-1" />}
            </div>

            {/* Step card */}
            <div className="border-border/60 bg-card mb-3 flex flex-1 flex-col gap-1.5 rounded-lg border px-5 py-4 shadow-sm transition-all duration-200 hover:shadow-md">
              <div className="text-muted-foreground flex items-center gap-2">
                {step.icon}
                <span className="text-foreground text-sm font-semibold tracking-tight">
                  {step.title}
                </span>
              </div>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <InlineMarkdown text={step.description} />
              </p>
              {step.tip && (
                <p className="text-muted-foreground/70 mt-0.5 text-xs italic">{step.tip}</p>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Result legend */}
      <div className="border-border/60 bg-card flex flex-col gap-3 rounded-lg border px-5 py-4 shadow-sm">
        <p className="text-muted-foreground text-xs font-bold tracking-wider uppercase">
          Reading results at a glance
        </p>
        <div className="flex flex-col gap-2">
          <div className="text-muted-foreground flex items-center gap-2 text-sm">
            <CheckCircle2 className="size-4 shrink-0 text-green-500" />
            <span>
              <strong className="text-foreground font-semibold">Passed</strong> — rule satisfied, no
              action needed.
            </span>
          </div>
          <div className="text-muted-foreground flex items-center gap-2 text-sm">
            <XCircle className="size-4 shrink-0 text-red-500" />
            <span>
              <strong className="text-foreground font-semibold">Failed</strong> — rule violated.
              Open the assertion for the AI recommendation.
            </span>
          </div>
          <div className="text-muted-foreground flex items-center gap-2 text-sm">
            <RefreshCw className="text-muted-foreground size-4 shrink-0" />
            <span>
              <strong className="text-foreground font-semibold">Pending</strong> — engine is still
              generating this assertion. Wait a moment and refresh.
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Page Component ───────────────────────────────────────────────────────────

export default function Help() {
  const [activeId, setActiveId] = useState<string>("home")
  const [searchQuery, setSearchQuery] = useState<string>("")
  const [debouncedQuery, setDebouncedQuery] = useState<string>("")

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedQuery(searchQuery)
    }, 200)
    return () => clearTimeout(handler)
  }, [searchQuery])

  const currentSection = sections.find((s) => s.id === activeId)

  const searchResults = useMemo(() => {
    if (!debouncedQuery.trim()) return []
    const query = debouncedQuery.toLowerCase()
    const flatList: Array<{
      sectionId: string
      sectionTitle: string
      icon: React.ReactNode
      title: string
      content: string
    }> = []

    sections.forEach((sec) => {
      sec.subsections.forEach((sub) => {
        if (sub.title.toLowerCase().includes(query) || sub.content.toLowerCase().includes(query)) {
          flatList.push({
            sectionId: sec.id,
            sectionTitle: sec.title,
            icon: sec.icon,
            title: sub.title,
            content: sub.content,
          })
        }
      })
    })

    return flatList
  }, [debouncedQuery])

  return (
    <div className="bg-background flex h-full min-h-0 w-full flex-1 overflow-hidden">
      {/* Sidebar */}
      <div className="border-border/40 bg-card/40 flex hidden h-full w-64 flex-col border-r md:flex">
        <div className="flex-1 overflow-y-auto p-4">
          <div className="text-muted-foreground mb-4 px-3 text-xs font-bold tracking-wider uppercase">
            Documentation
          </div>
          <nav className="space-y-1">
            <button
              onClick={() => {
                setActiveId("home")
                setSearchQuery("")
                setDebouncedQuery("")
              }}
              className={`flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-sm font-medium transition-all ${
                activeId === "home"
                  ? "bg-accent text-accent-foreground font-semibold shadow-sm"
                  : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
              }`}
            >
              <span
                className={`transition-colors ${activeId === "home" ? "text-primary" : "text-muted-foreground"}`}
              >
                <HelpCircle className="size-4" />
              </span>
              <span>Quick Hub & Search</span>
            </button>

            <div className="bg-border/40 my-3 h-px" />

            {sections.map((s) => {
              const isActive = activeId === s.id
              return (
                <button
                  key={s.id}
                  onClick={() => setActiveId(s.id)}
                  className={`flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-sm font-medium transition-all ${
                    isActive
                      ? "bg-accent text-accent-foreground font-semibold shadow-sm"
                      : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
                  }`}
                >
                  <span
                    className={`transition-colors ${isActive ? "text-primary" : "text-muted-foreground"}`}
                  >
                    {s.icon}
                  </span>
                  <span>{s.title}</span>
                </button>
              )
            })}
          </nav>
        </div>
      </div>

      {/* Main panel */}
      <div className="bg-background flex h-full min-h-0 flex-1 flex-col">
        <ScrollArea className="max-h-full min-h-0 flex-1">
          <main className="mx-auto w-full px-6 py-10 md:px-12 lg:py-14">
            {/* Home hub */}
            {activeId === "home" && (
              <div className="animate-in fade-in slide-in-from-bottom-2 space-y-8 duration-300">
                <div className="border-border/40 border-b pb-5">
                  <div className="mb-2 flex items-center gap-3">
                    <Terminal className="text-primary size-5" />
                    <span className="text-primary font-mono text-xs font-bold tracking-widest uppercase">
                      System Manual
                    </span>
                  </div>
                  <h1 className="text-foreground text-3xl font-extrabold tracking-tight">
                    Watchtower Control Hub
                  </h1>
                  <p className="text-muted-foreground mt-1 text-sm">
                    Query system telemetry parameters, deployment procedures, and framework
                    configurations.
                  </p>
                </div>

                <div className="relative">
                  <Search className="text-muted-foreground absolute top-3.5 left-4 h-5 w-5" />
                  <input
                    type="text"
                    placeholder="Search the documentation..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="border-border bg-card placeholder:text-muted-foreground/70 focus:ring-primary/40 focus:border-primary w-full rounded-xl border py-3.5 pr-4 pl-12 text-sm font-medium shadow-sm transition-all focus:ring-2 focus:outline-none"
                  />
                </div>

                {searchQuery.trim() ? (
                  <div className="space-y-4">
                    <h2 className="text-muted-foreground px-1 text-xs font-bold tracking-wider uppercase">
                      Query Results ({searchResults.length})
                    </h2>
                    {searchResults.length > 0 ? (
                      <div className="flex flex-col gap-4">
                        {searchResults.map((result, i) => (
                          <div
                            key={i}
                            className="border-border/60 bg-card animate-in fade-in overflow-hidden rounded-xl border shadow-sm duration-200"
                          >
                            <div className="bg-muted/40 border-border/40 flex items-center justify-between border-b px-5 py-2.5 text-xs">
                              <div className="text-muted-foreground flex items-center gap-2 font-medium">
                                {result.icon}
                                <span>{result.sectionTitle}</span>
                              </div>
                              <button
                                onClick={() => setActiveId(result.sectionId)}
                                className="text-primary font-semibold hover:underline"
                              >
                                Jump to module &rarr;
                              </button>
                            </div>
                            <div className="px-5 pt-3 pb-4">
                              <h3 className="text-foreground mb-2 text-sm font-bold">
                                <TextHighlighter text={result.title} search={debouncedQuery} />
                              </h3>
                              <SubsectionContent
                                content={result.content}
                                highlight={debouncedQuery}
                              />
                            </div>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="border-border bg-card/30 rounded-xl border border-dashed py-12 text-center">
                        <p className="text-muted-foreground text-sm">
                          No records matched your query parameters.
                        </p>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="grid grid-cols-1 gap-4 pt-2 sm:grid-cols-2">
                    {sections.map((s) => (
                      <button
                        key={s.id}
                        onClick={() => setActiveId(s.id)}
                        className="border-border/60 bg-card hover:border-primary/30 group rounded-xl border p-5 text-left shadow-sm transition-all hover:shadow-md"
                      >
                        <div className="bg-primary/10 text-primary group-hover:bg-primary group-hover:text-primary-foreground mb-4 w-fit rounded-lg p-2 transition-colors">
                          {s.icon}
                        </div>
                        <h3 className="text-foreground mb-1 text-sm font-bold">{s.title}</h3>
                        <p className="text-muted-foreground line-clamp-2 text-xs">
                          {s.id === "quick-run"
                            ? "Step-by-step walkthrough from setup to your first compliance report."
                            : `View details regarding ${s.subsections.map((sub) => sub.title).join(", ")}.`}
                        </p>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Quick Run */}
            {activeId === "quick-run" && <QuickRunSection />}

            {/* Standard section */}
            {activeId !== "home" && activeId !== "quick-run" && currentSection && (
              <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
                <div className="border-border/40 mb-8 flex items-center gap-4 border-b pb-5">
                  <div className="bg-primary/10 text-primary flex h-10 w-10 items-center justify-center rounded-xl shadow-inner">
                    {currentSection.icon}
                  </div>
                  <div>
                    <h1 className="text-foreground text-2xl font-bold tracking-tight">
                      {currentSection.title}
                    </h1>
                    <p className="text-muted-foreground mt-0.5 text-xs">
                      Watchtower Control Hub Guide
                    </p>
                  </div>
                </div>

                <div className="flex flex-col gap-4">
                  {currentSection.subsections.map((sub, i) => (
                    <SubsectionAccordion key={i} sub={sub} />
                  ))}
                </div>
              </div>
            )}
          </main>
        </ScrollArea>
      </div>
    </div>
  )
}
