name: Security

on:
  push: # every branch, every push
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 6 * * 1" # Monday 06:00 UTC

env:
  NODE_VERSION: "26"

permissions:
  contents: read

jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: NodeSecure SCA
        uses: NodeSecure/ci-action@177c57fe32c75cafabe87f6e4515d277cc37ae6c # 1.4.1
        with:
          strategy: npm
          reporters: console
          vulnerabilities: medium
          warnings: off # everything causes a warning I hate the js ecosystem
      
      - name: npm audit
        run: npm audit --audit-level moderate

  sast:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.164.0

    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Semgrep scan
        run: semgrep scan --config p/default --error
